ALTER TABLE character ADD COLUMN species_api_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE character ADD COLUMN is_shiny BOOLEAN NOT NULL DEFAULT false;

UPDATE character SET species_api_id = 168, is_shiny = false WHERE id = 1;
UPDATE character SET species_api_id = 445, is_shiny = false WHERE id = 2;
UPDATE character SET species_api_id = 200, is_shiny = false WHERE id = 3;
UPDATE character SET species_api_id = 248, is_shiny = false WHERE id = 4;
UPDATE character SET species_api_id = 566, is_shiny = false WHERE id = 5;
UPDATE character SET species_api_id = 921, is_shiny = false WHERE id = 6;
UPDATE character SET species_api_id = 216, is_shiny = false WHERE id = 7;
UPDATE character SET species_api_id = 627, is_shiny = false WHERE id = 8;
UPDATE character SET species_api_id = 133, is_shiny = false WHERE id = 9;
UPDATE character SET species_api_id = 133, is_shiny = false WHERE id = 10;
UPDATE character SET species_api_id = 710, is_shiny = false WHERE id = 11;
UPDATE character SET species_api_id = 215, is_shiny = false WHERE id = 12;
UPDATE character SET species_api_id = 10179, is_shiny = false WHERE id = 13;
UPDATE character SET species_api_id = 502, is_shiny = false WHERE id = 14;
UPDATE character SET species_api_id = 783, is_shiny = false WHERE id = 15;
UPDATE character SET species_api_id = 570, is_shiny = false WHERE id = 16;
UPDATE character SET species_api_id = 447, is_shiny = false WHERE id = 17;
UPDATE character SET species_api_id = 813, is_shiny = false WHERE id = 18;
UPDATE character SET species_api_id = 747, is_shiny = false WHERE id = 19;
UPDATE character SET species_api_id = 636, is_shiny = false WHERE id = 20;
UPDATE character SET species_api_id = 403, is_shiny = false WHERE id = 21;
UPDATE character SET species_api_id = 858, is_shiny = false WHERE id = 22;
UPDATE character SET species_api_id = 155, is_shiny = false WHERE id = 23;
UPDATE character SET species_api_id = 67, is_shiny = false WHERE id = 24;
UPDATE character SET species_api_id = 258, is_shiny = false WHERE id = 25;
UPDATE character SET species_api_id = 700, is_shiny = false WHERE id = 26;
UPDATE character SET species_api_id = 161, is_shiny = false WHERE id = 27;
UPDATE character SET species_api_id = 10103, is_shiny = false WHERE id = 28;
UPDATE character SET species_api_id = 653, is_shiny = false WHERE id = 29;
UPDATE character SET species_api_id = 190, is_shiny = false WHERE id = 30;
UPDATE character SET species_api_id = 529, is_shiny = false WHERE id = 31;
UPDATE character SET species_api_id = 327, is_shiny = false WHERE id = 32;
UPDATE character SET species_api_id = 570, is_shiny = false WHERE id = 33;
UPDATE character SET species_api_id = 200, is_shiny = false WHERE id = 34;
UPDATE character SET species_api_id = 700, is_shiny = false WHERE id = 35;
UPDATE character SET species_api_id = 10152, is_shiny = false WHERE id = 36;
UPDATE character SET species_api_id = 304, is_shiny = false WHERE id = 37;
UPDATE character SET species_api_id = 280, is_shiny = false WHERE id = 38;
UPDATE character SET species_api_id = 935, is_shiny = false WHERE id = 39;
UPDATE character SET species_api_id = 447, is_shiny = false WHERE id = 40;
UPDATE character SET species_api_id = 255, is_shiny = false WHERE id = 41;
UPDATE character SET species_api_id = 54, is_shiny = false WHERE id = 42;
UPDATE character SET species_api_id = 307, is_shiny = false WHERE id = 43;
UPDATE character SET species_api_id = 96, is_shiny = true WHERE id = 44;
UPDATE character SET species_api_id = 123, is_shiny = false WHERE id = 45;
UPDATE character SET species_api_id = 757, is_shiny = false WHERE id = 46;
UPDATE character SET species_api_id = 352, is_shiny = false WHERE id = 47;
UPDATE character SET species_api_id = 656, is_shiny = false WHERE id = 48;
UPDATE character SET species_api_id = 10152, is_shiny = false WHERE id = 49;
UPDATE character SET species_api_id = 757, is_shiny = false WHERE id = 50;
UPDATE character SET species_api_id = 27, is_shiny = false WHERE id = 51;
UPDATE character SET species_api_id = 1, is_shiny = false WHERE id = 52; -- debug character on test server
UPDATE character SET species_api_id = 531, is_shiny = false WHERE id = 53;
UPDATE character SET species_api_id = 4, is_shiny = false WHERE id = 54;



